[theme]
primaryColor = "#21A038"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F2F6F3"
textColor = "#15281C"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
